[package]
name = "synacor"
version = "0.1.0"
authors = ["James Wang <jameswang9909@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.21"
