[package]
name = "synacor"
version = "0.1.0"
authors = ["James Wang <jameswang9909@hotmail.com>"]
edition = "2018"

[lib]
name = "synacor"
path = "src/lib.rs"

[[bin]]
name = "synacor"
path = "src/main.rs"

[dependencies]
thiserror = "1.0.21"
